 name: Count Used Items
 version: 0.2
 description: Count Used Items by Paco

 author: Paco
 authors: [Paco]
 website: http://wwww.paskl.de

 main: de.paskl.useditems.Main

 commands:
   cui:
     description: Count Used Items Commands
     aliases: [count-used-items]
     usage: /<command> [0|off|1|on|show|reset]